import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { ReduxProvider } from "@/redux/provider";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Health U Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="favicon.png" type="image/x-icon" />
      </head>
      <body   suppressHydrationWarning
        className={` antialiased`}
      >
        <ReduxProvider>
        <Header/>
        {children}
        <Footer/>
        <Toaster/>
        </ReduxProvider>
      </body>
    </html>
  );
}
